### ISSUE TITLE
App defaults to Light Mode when enableBackgroundDelivery enabled

### ISSUE THREAD

**Issue by walterholohan** [kingstinct/react-native-healthkit#102]
Have spotted a bug where the app will default to Light mode even if Dark mode is set as the system default. This happens when:

1. enableBackgroundDelivery is enabled i.e. `HealthKit.enableBackgroundDelivery(HKWorkoutTypeIdentifier, HKUpdateFrequency.immediate)`
2. app has been force closed
3. record a workout an Apple Workouts app on Apple Watch
4. save the workout
5. the app will open in the background and process the new workout
6. open the app after a couple of minutes, then the app will open in Light mode i.e. `Appearance.getColorScheme() will be 'light'`

Not sure if this is a RN bug or iOS bug.

Has anyone else seen this happen before?

**Comment by robertherber** [comment]
Interesting, I don't think I've seen this happen but will keep my eyes open. It also does sound far-fetched that it should be linked specifically with this library - it would make more sense if it's a generic RN/iOS background issue as you're saying.

**Comment by walterholohan** [comment]
@robertherber managed to get to the bottom of it TLDR its a RN issue which someone already has raised a PR for

https://github.com/facebook/react-native/issues/46015
