### ISSUE TITLE
Can't build with RN 0.75.2

### ISSUE THREAD

**Issue by SergiOnGit** [kingstinct/react-native-healthkit#104]
app/node_modules/@kingstinct/react-native-healthkit/ios/Helpers.swift:40:28 'init(forReadingFrom:)' is only available in iOS 11.0 or newer

<img width="1143" alt="image" src="https://github.com/user-attachments/assets/7dfcc21b-b767-4442-bee3-46df09f7bff8">

**Comment by cstayyab** [comment]
Open Project in XCode, Go to Pods Project > Build Settings, select "kingstinct-react-native-healthkit and select iOS Deployment target to 11.0 or above (preferably 13.4)

**Comment by SergiOnGit** [comment]
Looks like this happens only with new arch enabled.
