### ISSUE TITLE
Can't get the right permission status if the user denied permission on modal.

### ISSUE THREAD

**Issue by ozgreenfeld** [kingstinct/react-native-healthkit#105]
Hi,

When asking permissions, I'm trying to get some indication for whether the user approved / denied permission on the Apple Permission modal.

I've tried to get the permission status on the following ways:
1. authorizationStatus returned from useHealthkitAuthorization but it returns 2 (unnecessary) whether the user approved or denied permissions.
2. HealthKit.requestAuthorization - returns true whether the user approved or denied.
3. HealthKit.authorizationStatusFor returns for me 1 (shouldRequest) whether the user approved or denied.

I would appreciate your help, am I missing something and there is a way to get the actual permissions status?
Thanks

code snippet that uses useHealthkitAuthorization: (copied from your website)
```
import { Text, Button, View, StyleSheet } from "react-native";
import {
  HKQuantityTypeIdentifier,
  useHealthkitAuthorization,
} from "@kingstinct/react-native-healthkit";

export default () => {
  const [authorizationStatus, requestAuthorization] = useHealthkitAuthorization(
    [HKQuantityTypeIdentifier.bloodGlucose]
  );

  return (
    <View>
      <Text>Authorization Status: {authorizationStatus}</Text>
      <Button onPress={requestAuthorization} title="Request Authorization" />
    </View>
  );
};
```

code snippet that uses authorizationStatusFor
```
async function askPermissions() {
  const isAvailable = await HealthKit.isHealthDataAvailable();
  console.log(isAvailable);
  if (!isAvailable) {
    return;
  }

  const permissionRequested = await HealthKit.requestAuthorization([
    HKCategoryTypeIdentifier.mindfulSession,
  ]);
  console.log(permissionRequested);

  const permissionGranted = await HealthKit.authorizationStatusFor(
    HKCategoryTypeIdentifier.mindfulSession
  );
  console.log(permissionGranted);
}
```

**Comment by ozgreenfeld** [comment]
After struggling with this a bit I've found out that this data is deliberately not shared by Apple due to privacy reasons.
https://developer.apple.com/documentation/healthkit/authorizing_access_to_health_data.

> As part of the privacy protections, your app doesn’t know whether someone granted or denied permission to read data from HealthKit. If they denied permission, attempts to read data from HealthKit return only samples that your app successfully saved to the HealthKit store.

**Comment by robertherber** [comment]
> After struggling with this a bit I've found out that this data is deliberately not shared by Apple due to privacy reasons. https://developer.apple.com/documentation/healthkit/authorizing_access_to_health_data.
> 
> > As part of the privacy protections, your app doesn’t know whether someone granted or denied permission to read data from HealthKit. If they denied permission, attempts to read data from HealthKit return only samples that your app successfully saved to the HealthKit store.

Yeah, that's the thing. And you will find that requesting data the user has denied sharing will only result in an empty data set, so no way to tell that way either.
