### ISSUE TITLE
Getting statistics for a workout

### ISSUE THREAD

**Issue by yakovsushenok** [kingstinct/react-native-healthkit#114]
Hi, is it possible to get statistics for a workout? For example [here ](https://developer.apple.com/documentation/healthkit/hkworkout/3929754-statistics) it seems like there's a way to query statistics for a certain workout. 

Maybe I'm not searching in the right place, but is it possible to get the heart rate statistics (heart rate at every second/minute of the workout) using this library?

**Comment by robertherber** [comment]
I see how this would be nice! PRs are welcome :)

My current recommendation is to simply fetch the samples (or statistics) for the time period of the workout.

**Comment by robertherber** [comment]
I take the thumbs up as this solved your issue, let me know otherwise @yakovsushenok!
