### ISSUE TITLE
App crash deleting samples with UUID that is a string not in a UUID format

### ISSUE THREAD

**Issue by mphill** [kingstinct/react-native-healthkit#118]
When writing sample data, a UUID can be specified.  This is a free-form text field, despite the name - it does not have to be an RFC UUID, and most are not.

Some apps use the SQLite primary key; others use an actual UUID.  If you attempt to call UUID.init with a non-RFC UUID it will return nil.  A result nil is passed to:

https://github.com/kingstinct/react-native-healthkit/blob/5ee5c1cbd880a850637cab341e72a270bd4415f1/ios/ReactNativeHealthkit.swift#L292C27-L292C54

and it crashes the app.

Workaround: use RFC UUIDs

**Comment by robertherber** [comment]
Sounds like a great idea! PRs are welcome :)
