### ISSUE TITLE
archive build fails with error "no such module combine"

### ISSUE THREAD

**Issue by kevinroehl** [Kingstinct/react-native-healthkit#15]
Works fine on simulator but fails on Archive with error "no such module combine"
(Xcode Version 12.5, React Native 0.64.0)

I already tried to build with iOS Deployment Target 9, 13 and 14

**Comment by robertherber** [comment]
Maybe this PR will solve it? It upgrades and runs RN 0.64 #13

**Comment by kevinroehl** [comment]
> Maybe this PR will solve it? It upgrades and runs RN 0.64 #13

Same error with this PR. 

I wrapped the import with canImport and was able to archive with Xcode. 
 `#if canImport(Combine)
import Combine;
#endif`

Is "Combine" relevant for react-native-healthkit or can it be removed?

**Comment by robertherber** [comment]
@kevinroehl I don't think it's currently needed. If you can verify that it works without I'd be happy to accept a PR! :)

**Comment by robertherber** [comment]
@kevinroehl Thanks for your contribution! This has been released in the 4.2.0 version - sorry about the delay between merge and release 🚀
