### ISSUE TITLE
Exception when calling enableBackgroundDelivery

### ISSUE THREAD

**Issue by deep108** [Kingstinct/react-native-healthkit#19]
I tried to enable background delivery by calling:
```
HealthKit.enableBackgroundDelivery(HKQuantityTypeIdentifier.bodyMass, HKUpdateFrequency.immediate)
```
 and got an exception:

```
enabledBackgroundDelivery:updateFrequency:withResolver:withRejector: is not a recognized Objective-C method
```

I investigated a little and found that the method signatures in ios/ReactNativeHealthkit.m and ios/ReactNativeHealthkit.swift don't match.

I'm putting together a pull request that fixes this and a few other methods.

**Comment by robertherber** [comment]
Thanks for your contribution @deep108. Your PR has been merged and is available in the 4.2.0 release 🚀
