### ISSUE TITLE
can we please add support for skiing/snowboarding

### ISSUE THREAD

**Issue by MasterHamster** [Kingstinct/react-native-healthkit#25]
I'd like to receive downhill skiing and snowboarding data :)

**Comment by robertherber** [comment]
Great idea @MasterHamster - I suppose this has been added in a recent HealthKit update? 

It should be very easy to just add the enum-mapping to the TypeScript definitions - it’s a perfect first PR 🙂

**Comment by MasterHamster** [comment]
@robertherber  Could you please add it? i really need this asap

**Comment by Andarius** [comment]
It seems to be already implemented: https://github.com/Kingstinct/react-native-healthkit/blob/1b68df944b5beac08cf70acdd14ac8dbe465fe0e/src/native-types.ts#L115

**Comment by robertherber** [comment]
@Andarius Right you are! 👍 Downhill skiing is also there 🙂
