### ISSUE TITLE
Add a disconnect function

### ISSUE THREAD

**Issue by MasterHamster** [Kingstinct/react-native-healthkit#26]
In case I want to revoke the connection and remove all existing permissions to apple health.

SCENARIO:
I requested reading permissions - Heartrate, and stepCount but only allowed permission for Heartrate.
I have no indication i didn't give permission to stepCount and (the requestAuthorization returns 1) and no way to reask for permissions (no disconnect)

**Comment by robertherber** [comment]
@MasterHamster Good suggestion - anything that helps build a good UX on Apple's privacy measures here.

Have you found such a function in the HealthKit docs? I had a quick look and couldn’t find any.

**Comment by robertherber** [comment]
[Seems to not be possible, so closing this now](https://stackoverflow.com/questions/41122213/how-to-revoke-healthkit-authorization)

Any ideas of how to improve DX around Apple's way to deal with privacy here would be very much appreciated 👍
