### ISSUE TITLE
delete method

### ISSUE THREAD

**Issue by jonstuebe** [Kingstinct/react-native-healthkit#29]
I'd love to be able to delete samples in case a user creates on in error. I also don't mind contributing but don't exactly know where to start. Thanks for the great work!

https://developer.apple.com/documentation/healthkit/hkhealthstore/1614155-delete

**Comment by jonstuebe** [comment]
Working on it here:

https://github.com/jonstuebe/react-native-healthkit/pull/1

**Comment by robertherber** [comment]
Looks awesome @jonstuebe, looking forward to a PR on this! :)

Today I fixed up the included example to make it easier to work with. Hope it helps with testing it out 👍

**Comment by jonstuebe** [comment]
There you go! Tested out on the RN side of things as well. For now I just implemented deleting a single sample with a UUID predicate. But could easily expand this to support others if folks need them.
