### ISSUE TITLE
Feature: Apple HealthKit Sharing

### ISSUE THREAD

**Issue by jonstuebe** [Kingstinct/react-native-healthkit#36]
In iOS 16 Apple has introduced a sharing option in which you can share data with friends/family. I was looking through the docs to see if it's an accessible from the API side but didn't see it. Do you know if it's around? I'd love to implement it if so.

**Comment by robertherber** [comment]
I've only seen it in the Apple Health app so far, and can't find anything in the documentation either.

**Comment by robertherber** [comment]
Let me know if you find something on this and I'll reopen the issue @jonstuebe :)

**Comment by Michota** [comment]
Can we reopen this issue?

**Comment by robertherber** [comment]
@Michota Let's do it if there's an API for it - have you found one?
