### ISSUE TITLE
Ability to deleteSamples without uuid (feature request)

### ISSUE THREAD

**Issue by VladyslavRoom4** [Kingstinct/react-native-healthkit#39]
Hello and thanks for great library!

I see we can deleteSamples by uuid, but is it possible to add ability deleteSamples without uuid, just use startDate, endDate for it? For example like it done on deleteSamples here (https://github.com/EddyVerbruggen/HealthKit).

**Comment by robertherber** [comment]
Seems like this Healthkit method would be suitable for this:
https://developer.apple.com/documentation/healthkit/hkhealthstore/1614162-deleteobjects

Would be happy to merge a PR on this 🙂

**Comment by VladyslavRoom4** [comment]
Hi @robertherber. Take a look at PR please) 
https://github.com/Kingstinct/react-native-healthkit/pull/42

**Comment by robertherber** [comment]
Nice work @VladyslavRoom4! It's been released in 5.3.0 :)
