### ISSUE TITLE
Unable to access VO2max data

### ISSUE THREAD

**Issue by VictorGarcia** [Kingstinct/react-native-healthkit#40]
Hi,

I'm trying to access vo2Max data on healthkit by requesting authorization to the `HKQuantityTypeIdentifier.vo2Max` quantity type, which is available in the library. I'm requesting the authorization along with other quantity type identifiers such as heart rate, body mass, etc. 

When launching the app for the first time, the iOS screen to request the user to authorize those scopes is coming up normally, however I get to see all the scopes I'm requesting EXCEPT for vo2Max. If I then try to access the vo2Max data using the queryQuantitySamples method I am obviously getting an error as the user has not authorized access to it.

Has anybody else experience this issue and are there any known workarounds to get VO2Max to work?

Thanks

**Comment by robertherber** [comment]
@VictorGarcia Thanks for reporting this! It should be fixed in the newly released 5.2.1, turns out Apple was using a slightly different naming convention on the VO2Max :)

**Comment by VictorGarcia** [comment]
Amazing, thanks!
