### ISSUE TITLE
Way to get all the quantity for each record.

### ISSUE THREAD

**Issue by giftsets** [Kingstinct/react-native-healthkit#49]
I was able to get the underwater depth and water temperature records of the Apple Watch Ultra through this library. But I couldn't find a way to get all the quantity for each record. how can i get them?

**Comment by robertherber** [comment]
I guess your use-case is syncing all available data? 

I'd recommend using the anchors that [are now available](https://github.com/Kingstinct/react-native-healthkit#healthkit-anchors-breaking-change-in-60) to step through large amounts of data, and iterate through all the records.

Does this answer the question?
