### ISSUE TITLE
Crash when using data

### ISSUE THREAD

**Issue by geronimosua** [Kingstinct/react-native-healthkit#53]
Hi! I'm having this problem and I don't know if it is a bug or I'm just not understanding how I should manage it.

I coded two hooks in the imperative way, one to request permissions and other to read the data that I have requested.

So I first request these permissions in the onboarding (first hook) and then consulting them when the user makes some update of his data like changing his username or nutritional goals (here is where the crash occurs).

I don't know if I'm doing wrong by use the hooks separately or what, thanks in advance for your cooperation.

Here's my code: 

- 1st hook
`import { useEffect } from "react";
import HealthKit, {
  HKQuantityTypeIdentifier,
  HKCategoryTypeIdentifier,
  HKCharacteristicTypeIdentifier,
} from "@kingstinct/react-native-healthkit";
import { logEventAsync } from "expo-analytics-amplitude";
import { useNavigation } from "@react-navigation/native";

const useAppleRequest = (request: boolean) => {
  const navigation = useNavigation();
  const routes = navigation.getState()?.routes;
  const prevRoute = routes[routes.length - 2];

  useEffect(() => {
    try {
      if (request) {
        const read = async () => {
          const isAvailable = await HealthKit.isHealthDataAvailable();

          if (!isAvailable) {
            return;
          }

          const permissionStatus = await HealthKit.requestAuthorization([
            HKQuantityTypeIdentifier.stepCount,
            HKCategoryTypeIdentifier.sleepAnalysis,
            HKCharacteristicTypeIdentifier.biologicalSex,
            HKCharacteristicTypeIdentifier.bloodType,
            HKCharacteristicTypeIdentifier.dateOfBirth,
            HKQuantityTypeIdentifier.height,
            HKQuantityTypeIdentifier.bodyMass,
            HKCategoryTypeIdentifier.pregnancy,
            HKCategoryTypeIdentifier.diarrhea,
          ]);
          return permissionStatus;
        };

        read();
        // I could cut this lines but just in case I don't take it out
        if (prevRoute === "AllowApple") {
          navigation.navigate("Name");
        } else if (prevRoute === "Father") {
          navigation.goBack();
        }
      }
    } catch (error) {
      logEventAsync(JSON.stringify(error));
    }
  }, [request]);
};

export default useAppleRequest;
`

- 2nd hook
`import { useEffect } from "react";

import HealthKit, {
  HKQuantityTypeIdentifier,
  HKCategoryTypeIdentifier,
  HKUnits,
  HKCharacteristicTypeIdentifier,
} from "@kingstinct/react-native-healthkit";
import { customAxios } from "../../App";
import { useAppSelector } from "./hooks";

const useAppleRead = (use: boolean) => {
  const userId = useAppSelector((state) => state.user.id);

  useEffect(() => {
    if (use) {
      const read = async () => {
        const sleepAuth = await HealthKit.authorizationStatusFor(
          HKCategoryTypeIdentifier.sleepAnalysis
        );
        const stepsAuth = await HealthKit.authorizationStatusFor(
          HKQuantityTypeIdentifier.stepCount
        );
        const heightAuth = await HealthKit.authorizationStatusFor(
          HKQuantityTypeIdentifier.height
        );
        const bodyMassAuth = await HealthKit.authorizationStatusFor(
          HKQuantityTypeIdentifier.bodyMass
        );
        const pregnancyAuth = await HealthKit.authorizationStatusFor(
          HKCategoryTypeIdentifier.pregnancy
        );
        const diarrheaAuth = await HealthKit.authorizationStatusFor(
          HKCategoryTypeIdentifier.diarrhea
        );
        const genderAuth = await HealthKit.authorizationStatusFor(
          HKCharacteristicTypeIdentifier.biologicalSex
        );
        const bloodTypeAuth = await HealthKit.authorizationStatusFor(
          HKCharacteristicTypeIdentifier.bloodType
        );
        const ageAuth = await HealthKit.authorizationStatusFor(
          HKCharacteristicTypeIdentifier.dateOfBirth
        );

        const sleep = sleepAuth
          ? await HealthKit.getMostRecentCategorySample(
              HKCategoryTypeIdentifier.sleepAnalysis
            )
          : null;

        const steps = stepsAuth
          ? await HealthKit.getMostRecentQuantitySample(
              HKQuantityTypeIdentifier.stepCount,
              HKUnits.Count
            )
          : null;

        const height = heightAuth
          ? await HealthKit.getMostRecentQuantitySample(
              HKQuantityTypeIdentifier.height,
              HKUnits.Count
            )
          : null;

        const bodyMass = bodyMassAuth
          ? await HealthKit.getMostRecentQuantitySample(
              HKQuantityTypeIdentifier.bodyMass,
              HKUnits.Count
            )
          : null;

        const pregnancy = pregnancyAuth
          ? await HealthKit.getMostRecentCategorySample(
              HKCategoryTypeIdentifier.pregnancy
            )
          : null;

        const diarrhea = diarrheaAuth
          ? await HealthKit.getMostRecentCategorySample(
              HKCategoryTypeIdentifier.diarrhea
            )
          : null;

        const gender = genderAuth ? await HealthKit.getBiologicalSex() : null;
        const bloodType = bloodTypeAuth ? await HealthKit.getBloodType() : null;
        const age = ageAuth ? await HealthKit.getDateOfBirth() : null;

        await customAxios.post("MY_ROUTE", {
          steps,
          sleep,
          gender,
          bloodType,
          age,
          height,
          bodyMass,
          pregnancy,
          diarrhea,
          userId,
        });
      };
      read();
    }
  }, [use]);
};

export default useAppleRead;`

**Comment by robertherber** [comment]
@geronimosua If it's a crash when updating it's most probably that `NSHealthUpdateUsageDescription` is missing from info.plist. 

I think the DX from Apple's side could be improved here, but yeah :) Here are the instructions [if you're using Expo Managed workflow ](https://github.com/Kingstinct/react-native-healthkit) and [here for the native/Bare Workflow](https://github.com/Kingstinct/react-native-healthkit#native-or-expo-bare-workflow) :)

**Comment by geronimosua** [comment]
Hey @robertherber  thanks for your response, maybe I explain myself bad, the update is in my app not in Apple Health I don't even write or ask for write permissions on Apple. And I already have NSHealthUpdateUsageDescription in my info.plist.

This is what I have in my info.plist

` "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.app.appname",
      "buildNumber": "92",
      "infoPlist": {
        "NSCameraUsageDescription": "This app uses the camera to take photos of the recipes when making a review.",
        "NSHealthShareUsageDescription": "This app uses the health data to automatically update the user values",
        "NSHealthUpdateUsageDescription": "This app uses the health data update to synchronize the user values"
      },
      "entitlements": {
        "com.apple.developer.healthkit": true,
        "com.apple.developer.healthkit.background-delivery": true
      }
    },`

**Comment by robertherber** [comment]
@geronimosua I have a hard time following your code, it would be easier if you clean up your example a bit, use the preview so it's formatted etc :)

The second suspect would be that you try to read some kind of data that you have not yet received confirmation (yes or no) from the user. If you call a query or initialize a hook before authorization has been asked for I think this will also result in a crash.

**Comment by robertherber** [comment]
I'm gonna close this. Please feel free reopen if you're still having issues and the above does not help 👍
