### ISSUE TITLE
Feature: exposing HKHeartbeatSeriesQuery for Heartbeat series data

### ISSUE THREAD

**Issue by oldratip** [Kingstinct/react-native-healthkit#57]
First of all, thanks for the great and modern library in TypeScript and Swift! Fantastic work.

One thing that seems to be missing is the ability to obtaining raw heartbeat data by first querying [`HKHeartbeatSeriesSample`](https://developer.apple.com/documentation/healthkit/hkheartbeatseriessample), which can be done with a normal anchored query, and then obtaining the underlying heartbeat data of each sample with a [`HKHeartbeatSeriesQuery`](https://developer.apple.com/documentation/healthkit/hkheartbeatseriesquery). 

I went ahead and implemented it myself, exposing the `queryHeartbeatSeriesSamples` method that returns the serialized samples comprising the heartbeat data as described above.

However, before submitting any PR, I wanted to be sure that there is no other way to do it with the already existing implementation that I might have missed.

Cheers!

**Comment by robertherber** [comment]
A PR for this is more than welcome @oldratip! :)
