### ISSUE TITLE
authorizationStatusFor has incorrect return type

### ISSUE THREAD

**Issue by ada-cienciala** [Kingstinct/react-native-healthkit#61]
### Problem

Official documentation shows it should return an enum that evaluates to numbers ([DOCS](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614154-authorizationstatus#return_value)): 
- notDetermined [0]
- sharingDenied [1]
- sharingAuthorized [2]

The function in the lib returns a boolean instead.

### Use case

When I first grant access in the app, it shows the permission sheet because it results in `notDetermined` (0). After that, when testing and disabling/enabling access through settings -> health -> data for my app, it always results in 1.

Now:
1. It is typed to return a `boolean` so why is it a `number`? I guess it's because JS converts somehow 1 and 2 to true and then converts that to a 1 but not sure.
2. Nevertheless, `sharingDenied` (1) and `sharingAuthorized` (2) SHOULD differ so that's false info. But Apple says they don't show if the user denied access so it's weird it's there in the first place

Is there any way to solve this and differentiate between denied and authorized?

**Comment by bohomi** [comment]
I've spent some time trying to get my head around this, perhaps it helps. The docs for `authorizationStatusFor` in this repo might not be fully accurate as it should return a `HKAuthorizationStatus` (ie. `notDetermined`, `sharingDenied` or `sharingAuthorized`) which is never actually used in the repo past the definition. However, I found that in my case `authorizationStatusFor` returns the right value.

From the docs it seems that Apple doesn't allow to see if a user has denied a READ permission so perhaps in your case you are looking at a read permission? 

In my example I am requesting WRITE permission for mindful minutes and I can see that `authorizationStatusFor` returns 0, 1 or 2 according to the Enum `HKAuthorizationStatus` in the Apple doc. 

```
 const [
    status, // this is of type `HKAuthorizationRequestStatus` (ie. unknown, shouldRequest, unnecessary)
    requestAuthorization,
  ] = HealthKit.useHealthkitAuthorization(
    [], 
    [HKCategoryTypeIdentifier.mindfulSession], // only asking for WRITE permission
  );
  
const authorisationStatus = await HealthKit.authorizationStatusFor(
    HKCategoryTypeIdentifier.mindfulSession,
); // this will be of type HKAuthorizationStatus (ie. notDetermined, sharingDenied or sharingAuthorized)

```

**Comment by josh-** [comment]
Opened #64 which should resolve this 🙂
