### ISSUE TITLE
HealthKit.requestAuthorization works once only

### ISSUE THREAD

**Issue by pratikdhody** [Kingstinct/react-native-healthkit#63]
Hi,

I believe there is a bug when calling `HealthKit.requestAuthorization([])` where the requestAuth modal only shows once when the app is running?
Steps to reproduce are as follows:
1. Currently calling `await HealthKit.authorizationStatusFor(HKCategoryTypeIdentifier.sleepAnalysis) `to check if we have access to sleepAnalysis
2. This is returning as 0 (false)
3. We then check `HealthKit.isHealthDataAvailable()` which is true.
4. We then render the request UI via `await HealthKit.requestAuthorization([HKCategoryTypeIdentifier.sleepAnalysis])`
5. In the first instance, this shows.
6. Image if use doesn't give permission and doesn't click Don't Allow. User kills app.
7. User re-opens app and the above logic runs but the `HealthKit.requestAuthorization` doesn't render the UI

Any thoughts on working around this?

**Comment by robertherber** [comment]
I'm fairly certain what you're describing is working as intended (by Apple that is). A few things that might help:
- Apple only lets apps present the dialog once per type of data. So it's probably a good idea to prepare the user before presenting the dialog.
- There is no way to tell if a user denied the app access to reading data - you will simply receive no data.
- `isHealthDataAvailable` is for indicating whether the device supports health data, [as per Apples docs](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable)

**Comment by pratikdhody** [comment]
> I'm fairly certain what you're describing is working as intended (by Apple that is). A few things that might help:
> 
> * Apple only lets apps present the dialog once per type of data. So it's probably a good idea to prepare the user before presenting the dialog.
> * There is no way to tell if a user denied the app access to reading data - you will simply receive no data.
> * `isHealthDataAvailable` is for indicating whether the device supports health data, [as per Apples docs](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable)

Thanks @robertherber. Regardless of the scenario I mentioned above, I'm also finding also that if the user granted access in current version of out app and then if we then released a newer version of the app then `HealthKit.authorizationStatusFor(HKCategoryTypeIdentifier.sleepAnalysis)` is false and so when we try and present the modal again, the modal doesn't show.

The only workaround that works is that we need to ask users to uninstall the app and then re-open and then the modal appears.

**Comment by robertherber** [comment]
@pratikdhody Yes, this is the same behaviour for any iOS app regarding showing the permission UI. You can only show it once per type of health data, that's it.

As for the authorizationStatusFor there is some discussion going on in #61 on whether it's reporting the correct value currently. I haven't had time to dig into it yet. 

I'd recommend using [`getRequestStatusForAuthorization`](https://developer.apple.com/documentation/healthkit/hkauthorizationrequeststatus) instead since it directly indicates whether you can/should ask the user for permissions (`shouldRequest`) or if you should just go ahead. This is what is exposed by Apple.
