### ISSUE TITLE
Build failing on fastlane in EAS

### ISSUE THREAD

**Issue by wjatx** [Kingstinct/react-native-healthkit#66]
I'm using the 7.0.0 version and getting a build error. Here are the relevant lines from the build logs:

The following build commands failed:
	CompileSwift normal arm64 (in target 'kingstinct-react-native-healthkit' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'kingstinct-react-native-healthkit' from project 'Pods')
(2 failures)
Exit status: 65

I can build a local simulator version and it works fine, but can't build for ad-hoc distribution.

Any idea why it would fail to compile?

**Comment by robertherber** [comment]
Not sure why this might be, I succeeded with an EAS build soon after the release. Does it succeed with the 6.x version?

**Comment by wjatx** [comment]
I got this to work today.

I tried moving back to the 6.x version and had the same result, so moved to the latest and then did the following:

Added to podfile:
```
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

Also, updated eas.json build profile to this:
```
    "development2": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": false,
        "resourceClass": "m-medium"
      }
    },
```

And used this in my app.json:
```
    "plugins": [
      [ "@kingstinct/react-native-healthkit",
        {
          "NSHealthShareUsageDescription": "This app uses HealthKit to store and sync your data"
        }
      ]
    ],
```

Thank you for responding so quickly. Also thank you for building this library!
