### ISSUE TITLE
EAS builds fail after integrating via expo plugin

### ISSUE THREAD

**Issue by mphill** [Kingstinct/react-native-healthkit#67]
After adding the module to my Expo SDK48 project, EAS builds started to fail. Simulator builds worked as they are more relaxed with provisioning profiles.

The error that occurred was:
`doesn't match the entitlements file's value for the com.apple.developer.healthkit.background-delivery entitlement`

```json
    "plugins": [
      "expo-build-properties",
      [
        "@kingstinct/react-native-healthkit",
        {
          "NSHealthShareUsageDescription": false,
          "NSHealthUpdateUsageDescription": "Write workout information to HealthKit",
          "background": false
        }
      ]
    ],
```

To fix the issue, and get EAS working again I had to change `background` to `true`

Just taking a guess here, but it could be related to: 
https://github.com/Kingstinct/react-native-healthkit/blob/1585007848e0ffeed9ae4f767aac881082475dec/app.plugin.js#L43

Should it be wrapped in an if statement to avoid it being added at all?

Or perhaps the EAS build is removing `com.apple.developer.healthkit.background-delivery `when the value is false?

One more note, the App Store will reject your app if you have `"NSHealthShareUsageDescription":  false`

Thanks for this incredible library!

**Comment by robertherber** [comment]
@mphill This should be fixed in the latest patch release, which makes sure we only modify info.plist when needed (i.e. not when opting out from background for example).

Closing this for now - let me know if you have any further issues :)
