### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by krisidmisso** [kingstinct/react-native-healthkit#85]
- When requesting authorization to read/write data types, the promise returns always a `true` value:
```
HealthKit.requestAuthorization(
          [
            HKQuantityTypeIdentifier.heartRate,
            HKQuantityTypeIdentifier.stepCount,
            HKQuantityTypeIdentifier.height,
          ]
        )
          .then(r => {
            console.log(r); // always returns true
          })
          .catch(e => {
            console.log('error: ', e);
          });
```
  Can it return the list of allowed permissions instead?
<br><br><br>

- Using a hook or imperative method to get if a specific permission (or list) is allowed or not after requesting authorization using the above doesnt seem to return the correct value:
```
HealthKit.getRequestStatusForAuthorization([
        HKQuantityTypeIdentifier.heartRate,
      ]).then(r => {
        console.log(r); //returns 2 => corresponding to `unnecessary`
      });
```

  The issue persists even when I enable manually the permission in phone settings->health

  The above method accepts an array of data type authorizations, but always return just 1 `HKAuthorizationRequestStatus`. Shouldnt it return a value for each of the data types in the request array?
  <br><br><br>
  
  ```
  HealthKit.authorizationStatusFor(HKQuantityTypeIdentifier.heartRate).then(
        permissionStatus => {
          console.log('Permission Status', 'appleMoveTime', permissionStatus);
          if (permissionStatus === 0) {
            HealthKit.requestAuthorization([
              HKQuantityTypeIdentifier.heartRate,
            ]).then(r => {
              console.log(r); //returns 1 =>  HKAuthorizationStatus = `sharindDenied`
            });
          }
        },
      );
  ```
The above method doesnt work as expected as well, returning a value of 1 after the permissions were requested for all, even for those that the user has accepted in the first step
<br><br><br>

I cannot request a specific authorization if it was asked before in a previous step using both imperative methods and hooks.

Is there another way to get the list of authorized data types or revoke and ask for the authorizations again?

**Comment by robertherber** [comment]
This is by design from Apple. 

There is only a way to tell whether you already requested the user to allow you to read that type of data (if you have already it will always return unnecessary).

There is also no way to discern between a type of data the user rejected and an empty data set (you’ll get an empty array in both cases).

**Comment by krisidmisso** [comment]
@robertherber is there any way to open directly the Health settings from within React Native? I have tried this URL Schema but it opens the app instead: `x-apple-health://Sources/MyAppName/` (`x-apple-health://` opens the same app screen)

Since there is no way to automatically detect if the user has approved/denied any of the permissions I think this would help instruct the user how and where to enable or check them.

**Comment by robertherber** [comment]
@krisidmisso I totally agree. We haven’t found such a url that works like that. And unless it is documented by Apple it runs a risk of being rejected when publishing to the AppStore. @RevanToma this aligns with your digging into this as well, right?

**Comment by RevanToma** [comment]
@krisidmisso @robertherber correct, sadly only way is to give instruction to the user on how to navigate to settings to enable diffrent permissions. And regarding the return value for each permission :
Apple's HealthKit does not provide an API to check which specific permissions were denied, instead you get back 0,1,2.
