### ISSUE TITLE
Not able to request write permissions

### ISSUE THREAD

**Issue by realPrimoh** [kingstinct/react-native-healthkit#86]
Hi, I'm trying to run `useHealthkitAuthorization` to be able to write data. I'm able to enable read permissions just fine, but I get an error when I try to request a write permission.

![Screenshot 2024-02-22 at 6 47 27 PM](https://github.com/kingstinct/react-native-healthkit/assets/24800437/802881d3-7e42-4d8b-bd06-5de508280f75)

`unrecognized selector sent to instance ... was thrown while invoking requestAuthorization on target ReactNativeHealthkit`.

I'm running this on an Expo Dev Client.

Here are my plugins:
```
"plugins": [
      "expo-router",
      ["@kingstinct/react-native-healthkit", {
        "NSHealthShareUsageDescription": "my app uses Apple Health to read and write data.",
        "NSHealthUpdateUsageDescription": true,
        "background": true
      }]
    ],
```

The code I'm using looks like this:
```
export default function Home() {
  const [authorizationStatus, requestAuthorization] = useHealthkitAuthorization(
    [
      HKQuantityTypeIdentifier.bodyMass,
      HKQuantityTypeIdentifier.appleMoveTime,
      HKQuantityTypeIdentifier.appleStandTime,
      HKQuantityTypeIdentifier.heartRate,
      HKQuantityTypeIdentifier.height,
      HKQuantityTypeIdentifier.vo2Max,
      HKQuantityTypeIdentifier.basalEnergyBurned,
      HKQuantityTypeIdentifier.activeEnergyBurned,
      HKQuantityTypeIdentifier.appleExerciseTime,
      HKQuantityTypeIdentifier.restingHeartRate,
      HKQuantityTypeIdentifier.timeInDaylight,
      HKQuantityTypeIdentifier.stepCount,
      HKQuantityTypeIdentifier.headphoneAudioExposure,
      HKCategoryTypeIdentifier.sleepAnalysis,
      HKCategoryTypeIdentifier.sexualActivity,
      HKCategoryTypeIdentifier.mindfulSession,
      HKActivitySummaryTypeIdentifier,
      HKWorkoutTypeIdentifier,
      HKWorkoutRouteTypeIdentifier,
      HKCharacteristicTypeIdentifier.dateOfBirth,
      HKCharacteristicTypeIdentifier.biologicalSex,
      HKCharacteristicTypeIdentifier.activityMoveMode,
    ], [HKQuantityTypeIdentifier.bodyMass]
  );
  ```

Thanks for the help!

**Comment by realPrimoh** [comment]
I wonder if this is because https://github.com/kingstinct/react-native-healthkit/blob/master/src/native-types.ts#L1993-L1998 doesn't have the required third parameter `completion: @escaping (Bool, Error?) -> Void` in Apple HealthKit's `requestAuthorization` anymore...?

**Comment by robertherber** [comment]
@realPrimoh The completions are abstracted away and handled as promises on the JS/TS-side so that should be ok. If you request anything other than bodyMass - does it work?

**Comment by realPrimoh** [comment]
Unfortunately not. I also tried the example app in the repo and get the
same error :(

Will try a fresh install tomorrow

**Comment by robertherber** [comment]
This could potentially be something in iOS 17? We’re mostly reading data on a day to day basis so we wouldn’t necessarily catch such a regression

**Comment by realPrimoh** [comment]
Unfortunately, I'm using iOS 16.4 on both simulator and my iPhone. Regardless, I just attempted it on a fresh build and it actually worked perfectly, so it's definitely something wrong with my project.

Apologies for the issue, closing this now.
